### ISSUE TITLE
Release a new version with support for require-sri-for directive

### ISSUE THREAD

**Issue by sideshowbarker** [shapesecurity/salvation#154]
I got a [user request today for CSP-checking feature in the the W3C HTML Checker to add support for the `require-sri-for` directive](https://github.com/validator/validator/issues/382) but the latest (2.1.0) release version of Salvation doesn’t have `require-sri-for` support, so resolving the HTML Checker issue is blocked on availability of a new Salvation release.

**Comment by michaelficarra** [comment]
:+1: we'll release 2.2.0 ASAP.

**Comment by kingthorin** [comment]
Hey if https://github.com/shapesecurity/salvation/pull/152 could be included in the next release (2.2.0) that'd be totally awesome. We're integrating salvation into a [ZAP extension](https://github.com/zaproxy/zaproxy/issues/527), which is why I put together the code change/PR. So for my 2 cents it would be great if https://github.com/shapesecurity/salvation/pull/152 made it for 2.2.0 along with the require-sri stuff :smiley:

**Comment by shekyan** [comment]
Released [v2.2.0](https://github.com/shapesecurity/salvation/releases/tag/v2.2.0)

**Comment by kingthorin** [comment]
Is the jar still being released?

**Comment by michaelficarra** [comment]
@kingthorin It's up there, but it takes a few hours to propagate or something. You can try this link: https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=com.shapesecurity&a=salvation&v=2.2.0&e=jar

**Comment by kingthorin** [comment]
Great, thanks!

**Comment by michaelficarra** [comment]
Also, I see it listed here, so it should be good: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.shapesecurity%22

**Comment by sideshowbarker** [comment]
Thanks—pushed an HTML checker update with this integrated to https://validator.w3.org/nu/ and https://checker.html5.org/
