### ISSUE TITLE
Non-empty policy when union merging frame-ancestors and default-src

### ISSUE THREAD

**Issue by cnsgithub** [shapesecurity/salvation#213]
My unit test:
```java
Policy x = Parser.parse("frame-ancestors https://foo.bar", "http://example.com");
Policy y = Parser.parse("default-src 'none'", "http://example.com");
Policy z = Parser.parse("script-src 'self'; img-src 'self'", "http://example.com");
x.union(y);
x.union(z);
assertEquals("frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'", x.show());
```

**Salvation 2.5.0 - unit test passes:**
```
Expected :frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'
Actual   :frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'
```

**Salvation 2.6.0 - unit test fails:**
```
Expected :frame-ancestors https://foo.bar; default-src; script-src 'self'; img-src 'self'
Actual   :frame-ancestors https://foo.bar
```

While in salvation 2.5.0 merge operation seems to be associative, it seems not to be in 2.6.0.

**Salvation 2.5.0:**
`(x ∪ y) ∪ z = x ∪ (y ∪ z)
`

**Salvation 2.6.0:**
`(x ∪ y) ∪ z ≠ x ∪ (y ∪ z)
`

| (x ∪ y) ∪ z |  x ∪ (y ∪ z) |
| ------------- |-------------|
| [cspvalidator.org](https://cspvalidator.org/#headerValue%5B%5D=frame-ancestors+https%3A%2F%2Ffoo.bar&headerValue%5B%5D=default-src+'none'&headerValue%5B%5D=script-src+'self'%3B+img-src+'self'&strategy=union) | [cspvalidator.org](https://cspvalidator.org/#headerValue%5B%5D=default-src+'none'&headerValue%5B%5D=frame-ancestors+https%3A%2F%2Ffoo.bar&headerValue%5B%5D=script-src+'self'%3B+img-src+'self'&strategy=union) |

_Originally posted by @cnsgithub in https://github.com/shapesecurity/salvation/issues/210#issuecomment-436885547_

**Comment by shekyan** [comment]
@cnsgithub will address once I'm back from my trip.

**Comment by shekyan** [comment]
To summarize: more than two years ago we introduced [this](https://github.com/w3c/webappsec-csp/commit/22c3ab8ff872668b2454227e87427e8677f4db7c) change to the specification, and never adjusted the logic in salvation. 

Before the change, `*` source-expression of a fetch directive was most permissive representation, and equivalent to missing directive. 

After the change, there is no semantic equivalent of a missing directive. For example, missing policy allows resources from anywhere, including `custom-scheme:`, while `default-src *` blocks any non-network scheme, unless explicitly whitelisted.

So, union merging `frame-ancestors 'self'` with `default-src *` now produces an empty policy, because first policy has most permissive `default-src`, which is missing, and second policy has most permissive `frame-ancestors`, because it is also missing.
