### ISSUE TITLE
cspvalidator.org: Checker is case sensitive

### ISSUE THREAD

**Issue by mdsnins** [shapesecurity/salvation#217]
By RFC2616,#4.2, header name is case-insensitive in standard. In fact, Facebook has CSP header with "content-security-policy", not "Content-Security-Policy", thus validator can't recognize the CSP. Could you fix it?

**Comment by shekyan** [comment]
The reason validator cannot find CSP in facebook's response is because there is no CSP in the response:) Facebook is trying to send browser-specific CSP and doesn't have a matching policy for the user-agent string that valdiator sends. We experimented in the past and at some point `Mozilla/5.0 (not Macintosh;not a Firefox, not a Chrome, but; https://cspvalidator.org)` was good enough for few websites that we noticed are switching policies on user-agent string. 

We intentionally don't want to pretend to be a real browser. For now, I changed `cspvalidator.org` to use `Mozilla/5.0 AppleWebKit/0 Chrome/0 Edge/0 Safari/0 Gecko/0 Firefox/0; +https://cspvalidator.org`, which is generic enough, contains most of the keywords that parsers might be looking for, and does not pretend to be a real user-agent string.
