### ISSUE TITLE
Question about union logic in version 2.7.x

### ISSUE THREAD

**Issue by CheShianHung** [shapesecurity/salvation#256]
In 2.7.x readme I see this union example in the Readme.
```
Policy p = Parser.parse("script-src a; default-src b", "http://example.com/");
Policy q = Parser.parse("script-src b;", "http://example.com/");
p.union(q);
p.show(); // script-src a b
```

Why it is `script-src a b` instead of `script-src a b; default-src b`? Wouldn't missing `default-src b` blocks the fallback for other attributes like `style-src` or `font-src`? This is also different from the union logic in 2.6.x as demonstrated with the validation tool: https://cspvalidator.org/#headerValue%5B%5D=script-src+a%3B+default-src+b&headerValue%5B%5D=script-src+b%3B&strategy=union

**Comment by bakkot** [comment]
Oh, I believe that's actually an intentional change. The idea of `union` is to allow anything allowed by either of the two inputs, and `script-src a b` does that: the second policy lacked a `default-src` and therefore allowed (for example) all styles and fonts, so the resulting union should allow all styles and fonts as well, regardless of the other policy being union'd with it.

The "union" logic was always kind of difficult to reason about (and impossible to do in some cases), which is why it was removed in version 3.

**Comment by CheShianHung** [comment]
Ah I see. Thank you for the explanation! I didn't realized if `default-src` is not specified it allows everything. By knowing this we have found a way to work around it for our usecase. 

Thank you and you can close this issue.
