### ISSUE TITLE
Fully support future CSP directives

### ISSUE THREAD

**Issue by shekyan** [shapesecurity/salvation#76]
Fully support future CSP directives like upgrade-insecure-requests, referrer, etc.

**Comment by mattrobenolt** [comment]
And `reflected-xss`. :)

**Comment by shekyan** [comment]
minus `referrer`.

**Comment by mattrobenolt** [comment]
I guess `reflected-xss` was removed from the spec too. TIL. :)

**Comment by laukstein** [comment]
Header `content-security-policy:referrer no-referrer` returns

    CSP parsing error: 1:56: The referrer directive is not in the CSP specification yet.

Expected no error. Spec https://w3c.github.io/webappsec-referrer-policy/, http://www.w3.org/TR/referrer-policy/, https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#referrer

Related issue reported in https://github.com/validator/validator/issues/202

**Comment by shekyan** [comment]
@laukstein, the reason we do not support it for now is that referrer is not part of the CSP spec itself, even [CSP 3](https://w3c.github.io/webappsec-csp/) does not mention it yet. CSP is just another delivery mechanism, among [others](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery). 

There were discussions on webappsec mailing list on whether it should be merged into CSP spec or not, and final decision is not made yet, AFAIK.

**Comment by sideshowbarker** [comment]
cc @mikewest
While I agree in principle with not supporting anything CSP-related that isn’t part of a specification that defines a standard, I’d argue that since for the `referrer` and `upgrade-insecure-requests` and `block-all-mixed-content` directives we do already have specifications that define standards (in terms of specifying standard semantics and standard processing behavior), then Salvation (and other tools) should support those—and not just be restricted to only supporting directives from the CSP spec itself.

It’s true that none of those directives is in a final W3C Recommendation yet (though `upgrade-insecure-requests` and `block-all-mixed-content` are at Candidate Recommendation), but a W3C spec doesn’t need to be a final W3C Recommendation to be considered a standard. CSS2 was supported as a standard in browsers for 10 years before it became a final W3C Recommendation, and HTML5 was also supported for years before it reached final Recommendation at the W3C, and… the list goes on.

I also recognize that there’s [a registry for CSP directives](https://www.iana.org/assignments/content-security-policy-directives/content-security-policy-directives.xhtml) now, and `referrer` and `upgrade-insecure-requests` and `block-all-mixed-content` aren’t yet in that registry—but I argue that since they all are from specifications that defines standards, they should not necessarily need to be in the CSP registry before tools can start supporting them.

(Incidentally, It’s also worth pointing out that a specification doesn’t even need to be published at the W3C at all in order for it to define a standard. For example, there are a [number of different specs published at the WHATWG](https://spec.whatwg.org/) that define standards just by virtue of clearly specifying standard requirements and being implemented in multiple user agents.)

**Comment by michaelficarra** [comment]
@sideshowbarker @laukstein

We recognise that there will be a number of non-standard directives with varying levels of support in implementations. In order to represent these extensions and be maximally useful, we will add an "unknown" directive and begin parsing as described in #93 (parse each [directive token](http://www.w3.org/TR/CSP2/#directive_token) individually). This will make errors in individual directive tokens non-fatal. Instead, this kind of error will be moved to the "warnings" list with a severity level of "error".

**Comment by michaelficarra** [comment]
This is done and will be available in the 2.0 release.
